apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - service-accounts.yaml
  - guardrails.yaml
  - env-store-rbac.yaml
  - leader-election-rbac.yaml
  - configmap.yaml
  - control-plane.yaml
  - frontend.yaml
  - ingress.yaml
  - opensandbox-template.yaml
