import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mirrorCargoVersion, mirrorCargoLockVersion } from './mirror-cargo-version.mjs';

const SAMPLE = [
  '[workspace]',
  'members = ["fkst-hosted-api"]',
  'resolver = "2"',
  '',
  '[workspace.package]',
  'version = "0.0.0"',
  'edition = "2021"',
  '',
  '[dependencies]',
  'axum = "0.7"',
  'serde = { version = "1" }',
  '',
].join('\n');

test('rewrites only the [workspace.package] version line', () => {
  const out = mirrorCargoVersion(SAMPLE, '1.2.3');
  assert.match(out, /\[workspace\.package\]\nversion = "1\.2\.3"\n/);
  assert.ok(out.includes('axum = "0.7"'), 'dependency string version must stay untouched');
  assert.ok(out.includes('serde = { version = "1" }'), 'inline-table dependency version must stay untouched');
  assert.ok(!out.includes('version = "0.0.0"'), 'old workspace version must be gone');
});

test('idempotent: re-applying the same version is byte-identical', () => {
  const once = mirrorCargoVersion(SAMPLE, '1.2.3');
  const twice = mirrorCargoVersion(once, '1.2.3');
  assert.equal(twice, once);
});

test('missing target version line throws', () => {
  assert.throws(
    () => mirrorCargoVersion('[dependencies]\naxum = "0.7"\n', '1.2.3'),
    /no version line found/
  );
});

const LOCK_SAMPLE = [
  '# This file is automatically @generated by Cargo.',
  '# It is not intended for manual editing.',
  'version = 4',
  '',
  '[[package]]',
  'name = "axum"',
  'version = "0.7.9"',
  'source = "registry+https://github.com/rust-lang/crates.io-index"',
  'checksum = "abc123"',
  '',
  '[[package]]',
  'name = "fkst-hosted-api"',
  'version = "0.0.0"',
  'dependencies = [',
  ' "axum",',
  ']',
  '',
].join('\n');

test('lock: rewrites only the source-less workspace-member block', () => {
  const out = mirrorCargoLockVersion(LOCK_SAMPLE, '1.2.3');
  assert.match(out, /name = "fkst-hosted-api"\nversion = "1\.2\.3"\n/);
  assert.match(out, /name = "axum"\nversion = "0\.7\.9"\n/, 'sourced package version must stay untouched');
  assert.ok(out.includes('\nversion = 4\n'), 'unquoted lockfile-format header must stay untouched');
  assert.ok(!out.includes('version = "0.0.0"'), 'old member version must be gone');
});

test('lock: idempotent — re-applying the same version is byte-identical', () => {
  const once = mirrorCargoLockVersion(LOCK_SAMPLE, '1.2.3');
  const twice = mirrorCargoLockVersion(once, '1.2.3');
  assert.equal(twice, once);
});

test('lock: no source-less [[package]] block throws', () => {
  const onlySourced = [
    'version = 4',
    '',
    '[[package]]',
    'name = "axum"',
    'version = "0.7.9"',
    'source = "registry+https://github.com/rust-lang/crates.io-index"',
    '',
  ].join('\n');
  assert.throws(() => mirrorCargoLockVersion(onlySourced, '1.2.3'), /no source-less/);
});
