apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../local
  - ../../migrations
patches:
  - target:
      version: v1
      kind: ConfigMap
      name: fkst-control-plane-config
      namespace: chronoai-fkst
    patch: |-
      - op: add
        path: /data/FKST_ENV_STORE_LEGACY_NAMESPACE
        value: chronoai-fkst
